// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshj46flg2Qih8QgkdNw9eRtP0mgkOfTs',
    appId: '1:442455534098:web:8aaa6ab8518681c1fc06cb',
    messagingSenderId: '442455534098',
    projectId: 'indian-tex',
    authDomain: 'indian-tex.firebaseapp.com',
    storageBucket: 'indian-tex.firebasestorage.app',
    measurementId: 'G-9NZRJ7F0ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM53JJxwEJMvKIYEVOGe2MqHJPGunWEaI',
    appId: '1:442455534098:android:e610e5640c315112fc06cb',
    messagingSenderId: '442455534098',
    projectId: 'indian-tex',
    storageBucket: 'indian-tex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVIR7Cr4iIsMyZduQgUWWwY3bYryEDjkA',
    appId: '1:442455534098:ios:b787bce6efae8b85fc06cb',
    messagingSenderId: '442455534098',
    projectId: 'indian-tex',
    storageBucket: 'indian-tex.firebasestorage.app',
    iosBundleId: 'com.example.indianTex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVIR7Cr4iIsMyZduQgUWWwY3bYryEDjkA',
    appId: '1:442455534098:ios:b787bce6efae8b85fc06cb',
    messagingSenderId: '442455534098',
    projectId: 'indian-tex',
    storageBucket: 'indian-tex.firebasestorage.app',
    iosBundleId: 'com.example.indianTex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBshj46flg2Qih8QgkdNw9eRtP0mgkOfTs',
    appId: '1:442455534098:web:ed8964181a81ac2cfc06cb',
    messagingSenderId: '442455534098',
    projectId: 'indian-tex',
    authDomain: 'indian-tex.firebaseapp.com',
    storageBucket: 'indian-tex.firebasestorage.app',
    measurementId: 'G-YR10QXBM4H',
  );
}
